Axe 897
campsi/campsi-mono pull request #103
Opened 2022-05-16 14:52 UTC by jlotery

Global test script renamed to "test" in package.json.
All tests refactored so that all tests can be run with a single mocha command. 
Running all tests produces same results as running single tests.

2022-05-19 13:51 UTC, ChristopheBraud requested changes
It would have been better to move index files you deleted in a special "launch test config" folder. The purpose is to test our code with Postman during development, or to help preparing tests' config. The goal in the PR is to move those files from test folder to simplify mochas command and have a better tree architecture

2022-05-19 13:51 UTC, ChristopheBraud commented on package.json
> +    "test": " mocha './test/**/*.js' --exit"
How do you ignore config folders ? You showed me a version that ignore those folders if I remember well ?

2022-05-20 09:28 UTC, ChristopheBraud approved these changes
LGTM

2022-05-23 06:52 UTC, jlotery commented on package.json
> +    "test": " mocha './test/**/*.js' --exit"
I realized I didn't need to do that as there are no test entry points in the folders that were being ignored. If you think it's better to exclude the directories that do not contain tests let me know and I'll revert back to that.

2022-05-23 06:58 UTC, merged