Jameslotery/axe 808 docs as a developper i want links to
campsi/campsi-mono pull request #126
Opened 2022-07-01 15:23 UTC by jlotery

The goal of this PR is to look for either with-links: true in the request header or withLink=true in the query string and then if either of those is set to true do the following:

- lookup the id of the doc that preceds the query and the id of the doc that comes next

- if there is a preceeding document then the value previous_id will contain the id of that document

- if there is a document that comes after the value next_id will contain the id of that document

- if either of the above are not found i.e. no preceeding or subsequent document then those values will be absent from the server response

I have not applied the logic to inhertiable docs as this feature is not used yet

2022-07-11 13:40 UTC, ChristopheBraud requested changes

2022-07-11 13:40 UTC, ChristopheBraud commented on services/docs/lib/services/document.js
> +    (headers['with-links'] && headers['with-links'] === 'true') || (query.withLinks && query.withLinks === 'true');
attention, headers peut être vide (appel via patch ou via caas-api en direct)

2022-07-11 13:40 UTC, ChristopheBraud commented on services/docs/lib/services/document.js
> +            doc = results[0];
Si j'ai seulement l'id 3 en base et que je demande l'id 4, il va me retourner le doc d'id 3 au lieu d'une 404, (a vérifier, j'ai pas tester)

2022-07-11 13:40 UTC, ChristopheBraud commented on services/docs/lib/services/document.js
> +                if (next && next._id) returnValue.next_id = next._id;
il s'agit d'une meta donnée, les ids ne doivent pas se retrouver dans le document mais dans les en têtes de retour, sous la même forme que pour getDocuments (balise link) les ids peuvent éventuellement être mis en plus mais toujours dans les headers (first/previous/next/last)

2022-07-11 13:40 UTC, ChristopheBraud commented on services/docs/lib/services/document.js
> +          }
De manière générale je pense qu'il faut mieux 'isoler' le code des links plutôt que de l'intégrer pour faire des micro optimisations. Vu que cette feature ne servira que pour de l'ui, les optims ne sont pas nécessaires. Le code sera plus lisible ainsi

2022-07-15 14:34 UTC, jlotery commented on services/docs/lib/services/document.js
> +          }
j'ai refactoré le code ainsi.

2022-07-15 14:35 UTC, jlotery commented on services/docs/lib/services/document.js
> +            doc = results[0];
c'est corrigé et un test case a ete ajouté pour ce cas precis

2022-07-18 14:32 UTC, ChristopheBraud requested changes

2022-07-18 14:32 UTC, ChristopheBraud commented on lib/modules/buildLink.js
> +module.exports = function buildSingleDocumentLink(req, id) {
URL lib (that is integrated in node) is far better than building url by hand

2022-07-19 14:33 UTC, jlotery commented on lib/modules/buildLink.js
> +module.exports = function buildSingleDocumentLink(req, id) {
Ok thanks for the suggestion however I have reused the exising code that was in place for building the pagination links

2022-07-19 14:34 UTC, jlotery commented on services/docs/lib/handlers.js
> +      if (result.nav && (result.nav.next || result.nav.previous)) {
ok, I will remove nav from the reply body and move next and previous ids into the headers as we discussed

2022-07-20 14:29 UTC, ChristopheBraud approved these changes
LGTM

2022-07-25 07:31 UTC, merged