Jameslotery/dev 1907
campsi/campsi-mono pull request #156
Opened 2022-10-10 14:42 UTC by jlotery

Goal of this PR was to implement dev-1907 to provide a mechanism to delete document locks. Only the same user that locked the document can delete the lock

2022-10-19 13:32 UTC, rombat requested changes

2022-10-19 13:32 UTC, rombat commented on services/docs/lib/services/document.js
> +  const match = { _id: ObjectId(id) };
I would also check the id validity with `createObjectId` and throw an error if invalid

2022-10-20 08:53 UTC, rombat requested changes

2022-10-20 08:53 UTC, rombat commented on services/docs/lib/services/document.js
> +    throw new createError.InternalServerError();
I'd rather use a BadRequest here, with an explicit error message like `invalid ObjectId`

2022-10-21 07:37 UTC, jlotery commented on services/docs/lib/services/document.js
> +    throw new createError.InternalServerError();
Yes, you're right.

2022-10-24 07:19 UTC, rombat approved these changes

2022-10-24 14:01 UTC, merged