Dev 2125 feat/add password regex option
campsi/campsi-mono pull request #166
Opened 2022-11-14 14:57 UTC by Achalhii

In this feat, we add a new password regexp option in the auth service.

The routes concerned are : 
- signup
- reset-password
- updatePassword

btw, a verification of the email field has been added

2022-11-14 15:51 UTC, jlotery requested changes
Can you please create some tests in the tests/auth folder that prove that the regex test works i.e. create a user that that has a password that you know will fail and one that you know will work and test the return reuslt

2022-11-21 08:07 UTC, gabila-r commented on services/auth/lib/local.js
> +  const passwordRegex = new RegExp(req.authProvider.options.passwordRegex);
What happens if `passwordRegex` is not in the config ?

2022-11-21 08:39 UTC, jlotery requested changes
In the tests can you also add a test for an invalid email address with as many edge cases as possible. Thanks :)

2022-11-21 08:56 UTC, Achalhii commented on services/auth/lib/local.js
> +  const passwordRegex = new RegExp(req.authProvider.options.passwordRegex);
if passwordRegex is undefined, automatically take '' as pattern. You can test it, however, I can't find any doc that explicitly states it. 
Then, I will therefore add security in my code, you never know!

2022-11-25 08:40 UTC, jlotery approved these changes
LGTM

2022-11-25 08:41 UTC, merged