Jameslotery/dev 2146
campsi/campsi-mono pull request #180
Opened 2022-12-12 14:35 UTC by jlotery

Check that the email address sent to the billing AP is a valid email before submitting to stripe. If invalid return a 400 error response.

2022-12-13 07:34 UTC, gabila-r requested changes
Little update to do :grim

2022-12-13 07:34 UTC, gabila-r commented on services/stripe-billing/lib/index.js
> +const { hasUncaughtExceptionCaptureCallback } = require('process');
Why did you require this ? 🤔

2022-12-13 07:34 UTC, gabila-r commented on services/stripe-billing/lib/index.js
> +      try{
```suggestion
      try {
```
Linter not trigger ?

2022-12-13 07:34 UTC, gabila-r commented on services/stripe-billing/lib/index.js
> +      try{
```suggestion
      try {
```
Same

2022-12-13 08:03 UTC, jlotery commented on services/stripe-billing/lib/index.js
> +const { hasUncaughtExceptionCaptureCallback } = require('process');
oops, my vscode editor added it when the autocompletion feature wrongly added that object :( I'll remove it . thx :)

2022-12-19 08:25 UTC, gabila-r approved these changes

2023-01-03 13:11 UTC, merged