Dev 3736 improvement/xss protection
campsi/campsi-mono pull request #236
Opened 2023-07-03 16:50 UTC by Achalhii

In this PR, we add an HTML-sanitizer in post/put/patch docs and versioned-docs endpoint to prevent XSS injection.

Do to this, we use https://www.npmjs.com/package/sanitize-html library.

I tested `sanitizeHTMLFromXSS()` by applying it on the GET endpoints of our api, then I did several tests on the BO.

2023-07-04 07:16 UTC, gabila-r requested changes

2023-07-04 07:16 UTC, gabila-r commented on services/auth/lib/handlers.js
> +function sanitizeHTMLFromXSS(obj) {
Why did you put this function inside the auth service ? 🤔 It has nothing to do in auth service for me !

2023-07-04 08:28 UTC, Achalhii commented on services/auth/lib/handlers.js
> +function sanitizeHTMLFromXSS(obj) {
My bad, I was looking for a "utils" file to put it in, but I couldn't find anything, so I fell back on this one.

Do you have a better suggestion ? Create a utils.js file ?

2023-07-04 08:35 UTC, Achalhii commented on services/auth/lib/handlers.js
> +function sanitizeHTMLFromXSS(obj) {
Ok, I find a good solution

2023-07-04 09:21 UTC, gabila-r approved these changes

2023-07-05 07:50 UTC, rombat requested changes

2023-07-05 07:50 UTC, rombat commented on lib/modules/sanitize.js
> +      return Object.entries(obj).reduce((acc, [key, value]) => {
beware that a Date has an object type.
but `Object.entries()` on a Date returns an empty array. I don't think you want that.
Don't know if we ever have the case where it's used, but you should handle it imho. I've already had an issue with this case. Same for ObjectId btw.
I did something like that:
`const exclude = Object.prototype.toString.call(value) === '[object Date]' || ObjectId.isValid(value);`

2023-07-05 09:44 UTC, Achalhii commented on lib/modules/sanitize.js
> +      return Object.entries(obj).reduce((acc, [key, value]) => {
I already meet this problem during my test and i fixed it. Look the `initialValue` of the reduce 😉.

2023-07-05 10:19 UTC, rombat approved these changes

2023-07-05 10:19 UTC, rombat commented on lib/modules/sanitize.js
> +      return Object.entries(obj).reduce((acc, [key, value]) => {
nice, I wasn't aware of that ! 👍🏼

2023-07-06 08:13 UTC, merged