feat: replace getCollectionName
campsi/campsi-mono pull request #278
Opened 2024-01-09 16:21 UTC by rombat

WIP

2024-01-10 07:56 UTC, rombat commented on services/auth/lib/modules/collectionNames.js
> +      throw new Error('Multiple AuthServices found');
@ChristopheBraud , are you ok to consider that this is a breaking change ?

2024-01-10 08:41 UTC, ChristopheBraud commented on services/auth/lib/modules/collectionNames.js
> +      throw new Error('Multiple AuthServices found');
Indeed, it is

2024-01-10 17:39 UTC, ChristopheBraud requested changes

2024-01-10 17:39 UTC, ChristopheBraud commented on test/helpers/emptyDatabase.js
> +  const collections = await db.listCollections({}, { nameOnly: true }).toArray();
attention : ça ne supprime pas les contraintes et ont peu passer à coté de bug du aux createIndex (ça m'est déjà arrivé)

2024-01-11 08:23 UTC, rombat commented on test/helpers/emptyDatabase.js
> +  const collections = await db.listCollections({}, { nameOnly: true }).toArray();
quel bug dû au createIndex ? 
au pire je vire les index, mais je ne vois pas de quel bug tu parles

2024-01-11 08:25 UTC, rombat commented on test/helpers/emptyDatabase.js
> +  const collections = await db.listCollections({}, { nameOnly: true }).toArray();
j'ai run les tests plusieurs fois d'affilée sans soucis

2024-01-11 09:30 UTC, ChristopheBraud commented on test/helpers/emptyDatabase.js
> +  const collections = await db.listCollections({}, { nameOnly: true }).toArray();
ah oui pas de risque dans l'état actuel mais si il y a un breaking change sur les index, ca fou la merde, par principe vaut mieux les supprimer aussi puisque le but de la fonction c'est de partir d'une base clean

2024-01-11 12:16 UTC, rombat commented on test/helpers/emptyDatabase.js
> +  const collections = await db.listCollections({}, { nameOnly: true }).toArray();
ok
après createIndex ne crée pas d'index s'il est déjà existant, donc ça ne devrait pas poser de problème. mais je peux les virer

2024-01-11 12:44 UTC, ChristopheBraud commented on test/helpers/emptyDatabase.js
> +  const collections = await db.listCollections({}, { nameOnly: true }).toArray();
si tu relache un contrainte d'unicité ca peut foutre le bordel si

2024-01-11 12:46 UTC, ChristopheBraud approved these changes

2024-01-11 14:03 UTC, merged