Feat/versioned docs service
campsi/campsi-mono pull request #63
Opened 2022-01-21 12:12 UTC by rombat

2022-01-28 08:06 UTC, kevinrambaud commented on lib/modules/responseHelpers.js
> +  send(res, 409, body);
[Precondition failed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412)responde  should return a 412 status code.

2022-01-28 09:07 UTC, kevinrambaud requested changes

2022-01-28 09:55 UTC, kevinrambaud reviewed
As discussed on Slack, let's take this opportunity to add all the tests related to the new service you added.

2022-01-28 09:55 UTC, kevinrambaud commented on services/versioned-docs/lib/handlers.js
> +});
What's the purpose of the `apidoc` property? I don't see any reference to it in the codebase.

2022-01-28 09:55 UTC, kevinrambaud commented on services/versioned-docs/lib/handlers.js
> +});
Same here. What's the purpose of the `apidoc` property? It looks like it's not used anywhere in the codebase.

2022-01-28 09:55 UTC, kevinrambaud commented on services/versioned-docs/lib/handlers.js
> +    if (e.message.includes('Precondition Failed'))
Hum, relying on the content of the message is kinda weird. What about using the [http-errors](https://www.npmjs.com/package/http-errors) package, pass the error to via the `next` function and (finally) use an [error handler](https://expressjs.com/en/guide/error-handling.html)?

2022-01-28 09:55 UTC, kevinrambaud commented on services/versioned-docs/lib/handlers.js
> +    res.set('ETag', `revision-${doc.revision}`);
Is there any reason you construct a string for the ETag value rather than returning `doc.revision` directly?

2022-01-28 10:27 UTC, rombat commented
> As discussed on Slack, let's take this opportunity to add all the tests related to the new service you added.

I'm on it

2022-01-28 15:31 UTC, rombat commented
> > As discussed on Slack, let's take this opportunity to add all the tests related to the new service you added.
> 
> I'm on it

@kevinrambaud done

2022-02-01 15:51 UTC, ChristopheBraud reviewed
I still have to run the test, will be back soon

2022-02-01 15:51 UTC, ChristopheBraud commented on services/versioned-docs/lib/services/resource.js
> +const forIn = require('for-in');
delete this

2022-02-02 09:46 UTC, ChristopheBraud approved these changes
LGTM

2022-02-02 13:51 UTC, merged